# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5bac07e28a2b8d82d0dd1cab80ba14074fde78c5f5e1035cd576ff8d45473e97fa4753596179f4921c1efcedea39bf4e6a48afb27ca46a8b9cbf5c98d7b99a

test:
  secret_key_base: c964732e0bc7c443e3749d5753d36a14f861ff5a53961aaa595a0e21836b875f118202f6b4a4b177d33c9a7d285090fda20ecb63f866f982e47d6f028609e300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
